/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    shopifyCollections: ShopifyCollection;
    brands: Brand;
    productPhotos: ProductPhoto;
    storePages: StorePage;
    storeArticles: StoreArticle;
    storeBlogs: StoreBlog;
    storeMenus: StoreMenu;
    posts: Post;
    banners: Banner;
    categories: Category;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    shopifyCollections: ShopifyCollectionsSelect<false> | ShopifyCollectionsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    productPhotos: ProductPhotosSelect<false> | ProductPhotosSelect<true>;
    storePages: StorePagesSelect<false> | StorePagesSelect<true>;
    storeArticles: StoreArticlesSelect<false> | StoreArticlesSelect<true>;
    storeBlogs: StoreBlogsSelect<false> | StoreBlogsSelect<true>;
    storeMenus: StoreMenusSelect<false> | StoreMenusSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      syncProduct: TaskSyncProduct;
      refreshProducts: TaskRefreshProducts;
      syncStoreResource: TaskSyncStoreResource;
      deleteStoreResource: TaskDeleteStoreResource;
      refreshStore: TaskRefreshStore;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Shopify の商品の入力画面です。開いたときに Shopify の最新の内容を取り込み、保存すると Shopify に反映します。商品を消すときは「状態」をアーカイブにしてください。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  kind: 'used' | 'new' | 'consignment';
  status: 'draft' | 'active' | 'archived';
  newArrival?: boolean | null;
  brand?: (number | null) | Brand;
  /**
   * 例: Italian Velor 3B Jacket
   */
  name?: string | null;
  autoTitle?: boolean | null;
  titleSuffix?: string | null;
  /**
   * Shopify の自動コレクションが商品名で判定しているので、[BRAND] と [USED] の形を崩さないでください。
   */
  title: string;
  /**
   * 1枚目が商品の代表画像になります。ドラッグで並べ替えできます。
   */
  images?:
    | {
        photo?: (number | null) | ProductPhoto;
        shopifyUrl?: string | null;
        alt?: string | null;
        shopifyMediaId?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 編集すると、下の HTML が作り直されて Shopify に送られます。説明文の中に埋め込まれた画像は、編集すると消えます（商品の写真は「写真」に入れてください）。
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionHtml?: string | null;
  seoDescription?: string | null;
  /**
   * 1点ものは空のままにします。
   */
  options?:
    | {
        name: string;
        values?: string[] | null;
        id?: string | null;
      }[]
    | null;
  variants?:
    | {
        optionValues?: string[] | null;
        price: number;
        compareAtPrice?: number | null;
        /**
         * 作成時だけ送ります
         */
        sku?: string | null;
        /**
         * 作成時だけ送ります
         */
        cost?: number | null;
        /**
         * 作成時だけ送ります
         */
        initialQuantity?: number | null;
        inventoryQuantity?: number | null;
        shopifyVariantId?: string | null;
        inventoryItemId?: string | null;
        id?: string | null;
      }[]
    | null;
  condition?: ('SS' | 'S' | 'A' | 'B' | 'C') | null;
  /**
   * 例: 80s、ヴィンテージ
   */
  era?: string | null;
  conditionNote?: string | null;
  /**
   * 採寸する順に並べます。着丈・身幅・肩幅・袖丈（トップス）、ウエスト・股上・股下・もも周り・裾周り（パンツ）
   */
  measurements?:
    | {
        name: string;
        value: number;
        id?: string | null;
      }[]
    | null;
  style?: string[] | null;
  features?: string[] | null;
  /**
   * 例: Shirts、Coats & Jackets
   */
  productType?: string | null;
  vendor?: string | null;
  categoryId?: string | null;
  categoryName?: string | null;
  /**
   * 区分（USED / NOT USED / 委託）と「新着」は上の項目に合わせて自動で付け外しします。
   */
  tags?: string[] | null;
  supplier?: string | null;
  deliveryNumber?: string | null;
  deliveryDate?: string | null;
  shopify?: {
    syncStatus?: ('synced' | 'pending' | 'dry-run' | 'conflict' | 'error') | null;
    syncMessage?: string | null;
    /**
     * 選んで保存すると実行します。
     */
    resolve?: ('overwrite' | 'import') | null;
    productId?: string | null;
    handle?: string | null;
    updatedAt?: string | null;
    lastSyncedAt?: string | null;
    fingerprint?: string | null;
    metafields?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * 商品名の [ ] に入れる表記（例: River）。空なら名前を使います。
   */
  titleLabel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productPhotos".
 */
export interface ProductPhoto {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Shopify のコレクションの入力画面です。開いたときに Shopify の最新の内容を取り込み、保存すると Shopify に反映します。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopifyCollections".
 */
export interface ShopifyCollection {
  id: number;
  /**
   * 作ったあとは変えられません。
   */
  kind: 'smart' | 'manual';
  title: string;
  /**
   * URL の末尾です。変えると、古い URL から新しい URL へ自動で転送されます。
   */
  handle?: string | null;
  /**
   * 画像や埋め込みのある既存の本文は「HTML を直接」で取り込んでいます。「見たまま」に切り替えると、見たままで扱えない部分（画像・埋め込み・装飾）は消えます。
   */
  descriptionHtmlMode?: ('visual' | 'html') | null;
  /**
   * 写真は「画像」から入れられます（85-store.com と同じ R2 に置かれます）。
   */
  descriptionHtmlRich?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionHtml?: string | null;
  /**
   * 選んで保存すると Shopify の画像を差し替えます（画像は Shopify にコピーされます）。
   */
  image?: (number | null) | Media;
  imageUrl?: string | null;
  imageAlt?: string | null;
  sortOrder:
    'BEST_SELLING' | 'CREATED_DESC' | 'CREATED' | 'PRICE_DESC' | 'PRICE_ASC' | 'ALPHA_ASC' | 'ALPHA_DESC' | 'MANUAL';
  appliedDisjunctively?: boolean | null;
  /**
   * 商品名で判定する条件（[BRAND] や USED）は、商品名の付け方と合わせてください。サイズ・カテゴリの条件は、値が Shopify の ID になります（右の名前で確認できます）。
   */
  rules?:
    | {
        column:
          | 'TITLE'
          | 'TAG'
          | 'TYPE'
          | 'VENDOR'
          | 'PRODUCT_CATEGORY_ID'
          | 'PRODUCT_CATEGORY_ID_WITH_DESCENDANTS'
          | 'PRODUCT_METAFIELD_DEFINITION'
          | 'VARIANT_PRICE'
          | 'VARIANT_COMPARE_AT_PRICE'
          | 'IS_PRICE_REDUCED'
          | 'VARIANT_INVENTORY'
          | 'VARIANT_WEIGHT'
          | 'VARIANT_TITLE'
          | 'VARIANT_METAFIELD_DEFINITION'
          | 'PRODUCT_TAXONOMY_NODE_ID';
        relation:
          | 'CONTAINS'
          | 'NOT_CONTAINS'
          | 'EQUALS'
          | 'NOT_EQUALS'
          | 'STARTS_WITH'
          | 'ENDS_WITH'
          | 'GREATER_THAN'
          | 'LESS_THAN'
          | 'IS_SET'
          | 'IS_NOT_SET';
        condition: string;
        conditionLabel?: string | null;
        /**
         * 既存のサイズの条件の行からコピーしてください。
         */
        conditionObjectId?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 並び順が「手動」のときは、この順番で並びます。
   */
  products?: (number | Product)[] | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * テーマのテンプレート（例: contact）。ふつうは空のままにします。
   */
  templateSuffix?: string | null;
  shopify?: {
    syncStatus?: ('synced' | 'pending' | 'dry-run' | 'conflict' | 'error') | null;
    syncMessage?: string | null;
    /**
     * 選んで保存すると実行します。
     */
    resolve?: ('overwrite' | 'import') | null;
    gid?: string | null;
    updatedAt?: string | null;
    lastSyncedAt?: string | null;
    fingerprint?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  sourceUrl?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    avif480?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    avif800?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    avif1200?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    avif1600?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    webp480?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    webp800?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    webp1200?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    webp1600?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Shopify のストアのページです。保存すると Shopify に反映します。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storePages".
 */
export interface StorePage {
  id: number;
  title: string;
  /**
   * URL の末尾です。変えると、古い URL から新しい URL へ自動で転送されます。
   */
  handle?: string | null;
  /**
   * 画像や埋め込みのある既存の本文は「HTML を直接」で取り込んでいます。「見たまま」に切り替えると、見たままで扱えない部分（画像・埋め込み・装飾）は消えます。
   */
  bodyMode?: ('visual' | 'html') | null;
  /**
   * 写真は「画像」から入れられます（85-store.com と同じ R2 に置かれます）。
   */
  bodyRich?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  body?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  isPublished?: boolean | null;
  /**
   * テーマのテンプレート（例: contact）。ふつうは空のままにします。
   */
  templateSuffix?: string | null;
  shopify?: {
    syncStatus?: ('synced' | 'pending' | 'dry-run' | 'conflict' | 'error') | null;
    syncMessage?: string | null;
    /**
     * 選んで保存すると実行します。
     */
    resolve?: ('overwrite' | 'import') | null;
    gid?: string | null;
    updatedAt?: string | null;
    lastSyncedAt?: string | null;
    fingerprint?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Shopify のストアのブログの記事です（85-store.com の記事は「サイト」の「記事」）。保存すると Shopify に反映します。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storeArticles".
 */
export interface StoreArticle {
  id: number;
  title: string;
  /**
   * 画像や埋め込みのある既存の本文は「HTML を直接」で取り込んでいます。「見たまま」に切り替えると、見たままで扱えない部分（画像・埋め込み・装飾）は消えます。
   */
  bodyMode?: ('visual' | 'html') | null;
  /**
   * 写真は「画像」から入れられます（85-store.com と同じ R2 に置かれます）。
   */
  bodyRich?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  body?: string | null;
  /**
   * 一覧に出る短い紹介文です。例: <p>…</p>
   */
  summary?: string | null;
  /**
   * 選んで保存すると Shopify の画像を差し替えます（画像は Shopify にコピーされます）。
   */
  image?: (number | null) | Media;
  imageUrl?: string | null;
  imageAlt?: string | null;
  /**
   * URL の末尾です。変えると、古い URL から新しい URL へ自動で転送されます。
   */
  handle?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  blog: number | StoreBlog;
  isPublished?: boolean | null;
  author?: string | null;
  tags?: string[] | null;
  /**
   * テーマのテンプレート（例: contact）。ふつうは空のままにします。
   */
  templateSuffix?: string | null;
  shopify?: {
    syncStatus?: ('synced' | 'pending' | 'dry-run' | 'conflict' | 'error') | null;
    syncMessage?: string | null;
    /**
     * 選んで保存すると実行します。
     */
    resolve?: ('overwrite' | 'import') | null;
    gid?: string | null;
    updatedAt?: string | null;
    lastSyncedAt?: string | null;
    fingerprint?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storeBlogs".
 */
export interface StoreBlog {
  id: number;
  title: string;
  /**
   * URL の末尾です。変えると、古い URL（記事を含む）から新しい URL へ自動で転送されます。
   */
  handle?: string | null;
  commentPolicy: 'CLOSED' | 'MODERATED' | 'AUTO_PUBLISHED';
  /**
   * テーマのテンプレート（例: contact）。ふつうは空のままにします。
   */
  templateSuffix?: string | null;
  shopify?: {
    syncStatus?: ('synced' | 'pending' | 'dry-run' | 'conflict' | 'error') | null;
    syncMessage?: string | null;
    /**
     * 選んで保存すると実行します。
     */
    resolve?: ('overwrite' | 'import') | null;
    gid?: string | null;
    updatedAt?: string | null;
    lastSyncedAt?: string | null;
    fingerprint?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Shopify のストアのメニューです。保存すると Shopify に反映します。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storeMenus".
 */
export interface StoreMenu {
  id: number;
  title: string;
  /**
   * テーマがメニューを探すときの名前です（main-menu・footer など）。
   */
  handle?: string | null;
  isDefault?: boolean | null;
  items?:
    | {
        title: string;
        type:
          | 'COLLECTION'
          | 'PRODUCT'
          | 'PAGE'
          | 'BLOG'
          | 'ARTICLE'
          | 'HTTP'
          | 'FRONTPAGE'
          | 'CATALOG'
          | 'COLLECTIONS'
          | 'SEARCH'
          | 'SHOP_POLICY'
          | 'METAOBJECT'
          | 'CUSTOMER_ACCOUNT_PAGE';
        resource?:
          | ({
              relationTo: 'shopifyCollections';
              value: number | ShopifyCollection;
            } | null)
          | ({
              relationTo: 'products';
              value: number | Product;
            } | null)
          | ({
              relationTo: 'storePages';
              value: number | StorePage;
            } | null)
          | ({
              relationTo: 'storeBlogs';
              value: number | StoreBlog;
            } | null)
          | ({
              relationTo: 'storeArticles';
              value: number | StoreArticle;
            } | null);
        url?: string | null;
        tags?: string[] | null;
        resourceId?: string | null;
        itemId?: string | null;
        subItems?:
          | {
              title: string;
              type:
                | 'COLLECTION'
                | 'PRODUCT'
                | 'PAGE'
                | 'BLOG'
                | 'ARTICLE'
                | 'HTTP'
                | 'FRONTPAGE'
                | 'CATALOG'
                | 'COLLECTIONS'
                | 'SEARCH'
                | 'SHOP_POLICY'
                | 'METAOBJECT'
                | 'CUSTOMER_ACCOUNT_PAGE';
              resource?:
                | ({
                    relationTo: 'shopifyCollections';
                    value: number | ShopifyCollection;
                  } | null)
                | ({
                    relationTo: 'products';
                    value: number | Product;
                  } | null)
                | ({
                    relationTo: 'storePages';
                    value: number | StorePage;
                  } | null)
                | ({
                    relationTo: 'storeBlogs';
                    value: number | StoreBlog;
                  } | null)
                | ({
                    relationTo: 'storeArticles';
                    value: number | StoreArticle;
                  } | null);
              url?: string | null;
              tags?: string[] | null;
              resourceId?: string | null;
              itemId?: string | null;
              subSubItems?:
                | {
                    title: string;
                    type:
                      | 'COLLECTION'
                      | 'PRODUCT'
                      | 'PAGE'
                      | 'BLOG'
                      | 'ARTICLE'
                      | 'HTTP'
                      | 'FRONTPAGE'
                      | 'CATALOG'
                      | 'COLLECTIONS'
                      | 'SEARCH'
                      | 'SHOP_POLICY'
                      | 'METAOBJECT'
                      | 'CUSTOMER_ACCOUNT_PAGE';
                    resource?:
                      | ({
                          relationTo: 'shopifyCollections';
                          value: number | ShopifyCollection;
                        } | null)
                      | ({
                          relationTo: 'products';
                          value: number | Product;
                        } | null)
                      | ({
                          relationTo: 'storePages';
                          value: number | StorePage;
                        } | null)
                      | ({
                          relationTo: 'storeBlogs';
                          value: number | StoreBlog;
                        } | null)
                      | ({
                          relationTo: 'storeArticles';
                          value: number | StoreArticle;
                        } | null);
                    url?: string | null;
                    tags?: string[] | null;
                    resourceId?: string | null;
                    itemId?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  shopify?: {
    syncStatus?: ('synced' | 'pending' | 'dry-run' | 'conflict' | 'error') | null;
    syncMessage?: string | null;
    /**
     * 選んで保存すると実行します。
     */
    resolve?: ('overwrite' | 'import') | null;
    gid?: string | null;
    updatedAt?: string | null;
    lastSyncedAt?: string | null;
    fingerprint?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  eyecatch?: (number | null) | Media;
  description?: string | null;
  excerpt?: string | null;
  /**
   * 半角英数とハイフン。空なら日付から作ります。
   */
  slug: string;
  publishedAt?: string | null;
  categories?: (number | Category)[] | null;
  tags?: string[] | null;
  featured?: boolean | null;
  author?: string | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 名前はサイトの URL になります。Event1st / Event2nd は Reserve ページのイベント一覧に使っています。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * 縦長の画像はトップのヒーロー（先頭から2枚）、それ以外は Pick Up に並びます。ドラッグで並び替えできます。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  _order?: string | null;
  image: number | Media;
  title?: string | null;
  subtitle?: string | null;
  detailButtonUrl?: string | null;
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tailscale のアカウントのメールアドレスを登録すると、その人が管理画面に入れるようになります。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  email: string;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          'inline' | 'syncProduct' | 'refreshProducts' | 'syncStoreResource' | 'deleteStoreResource' | 'refreshStore';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | ('inline' | 'syncProduct' | 'refreshProducts' | 'syncStoreResource' | 'deleteStoreResource' | 'refreshStore')
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'shopifyCollections';
        value: number | ShopifyCollection;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'productPhotos';
        value: number | ProductPhoto;
      } | null)
    | ({
        relationTo: 'storePages';
        value: number | StorePage;
      } | null)
    | ({
        relationTo: 'storeArticles';
        value: number | StoreArticle;
      } | null)
    | ({
        relationTo: 'storeBlogs';
        value: number | StoreBlog;
      } | null)
    | ({
        relationTo: 'storeMenus';
        value: number | StoreMenu;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  kind?: T;
  status?: T;
  newArrival?: T;
  brand?: T;
  name?: T;
  autoTitle?: T;
  titleSuffix?: T;
  title?: T;
  images?:
    | T
    | {
        photo?: T;
        shopifyUrl?: T;
        alt?: T;
        shopifyMediaId?: T;
        id?: T;
      };
  description?: T;
  descriptionHtml?: T;
  seoDescription?: T;
  options?:
    | T
    | {
        name?: T;
        values?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        optionValues?: T;
        price?: T;
        compareAtPrice?: T;
        sku?: T;
        cost?: T;
        initialQuantity?: T;
        inventoryQuantity?: T;
        shopifyVariantId?: T;
        inventoryItemId?: T;
        id?: T;
      };
  condition?: T;
  era?: T;
  conditionNote?: T;
  measurements?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  style?: T;
  features?: T;
  productType?: T;
  vendor?: T;
  categoryId?: T;
  categoryName?: T;
  tags?: T;
  supplier?: T;
  deliveryNumber?: T;
  deliveryDate?: T;
  shopify?:
    | T
    | {
        syncStatus?: T;
        syncMessage?: T;
        resolve?: T;
        productId?: T;
        handle?: T;
        updatedAt?: T;
        lastSyncedAt?: T;
        fingerprint?: T;
        metafields?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopifyCollections_select".
 */
export interface ShopifyCollectionsSelect<T extends boolean = true> {
  kind?: T;
  title?: T;
  handle?: T;
  descriptionHtmlMode?: T;
  descriptionHtmlRich?: T;
  descriptionHtml?: T;
  image?: T;
  imageUrl?: T;
  imageAlt?: T;
  sortOrder?: T;
  appliedDisjunctively?: T;
  rules?:
    | T
    | {
        column?: T;
        relation?: T;
        condition?: T;
        conditionLabel?: T;
        conditionObjectId?: T;
        id?: T;
      };
  products?: T;
  seoTitle?: T;
  seoDescription?: T;
  templateSuffix?: T;
  shopify?:
    | T
    | {
        syncStatus?: T;
        syncMessage?: T;
        resolve?: T;
        gid?: T;
        updatedAt?: T;
        lastSyncedAt?: T;
        fingerprint?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  titleLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productPhotos_select".
 */
export interface ProductPhotosSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storePages_select".
 */
export interface StorePagesSelect<T extends boolean = true> {
  title?: T;
  handle?: T;
  bodyMode?: T;
  bodyRich?: T;
  body?: T;
  seoTitle?: T;
  seoDescription?: T;
  isPublished?: T;
  templateSuffix?: T;
  shopify?:
    | T
    | {
        syncStatus?: T;
        syncMessage?: T;
        resolve?: T;
        gid?: T;
        updatedAt?: T;
        lastSyncedAt?: T;
        fingerprint?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storeArticles_select".
 */
export interface StoreArticlesSelect<T extends boolean = true> {
  title?: T;
  bodyMode?: T;
  bodyRich?: T;
  body?: T;
  summary?: T;
  image?: T;
  imageUrl?: T;
  imageAlt?: T;
  handle?: T;
  seoTitle?: T;
  seoDescription?: T;
  blog?: T;
  isPublished?: T;
  author?: T;
  tags?: T;
  templateSuffix?: T;
  shopify?:
    | T
    | {
        syncStatus?: T;
        syncMessage?: T;
        resolve?: T;
        gid?: T;
        updatedAt?: T;
        lastSyncedAt?: T;
        fingerprint?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storeBlogs_select".
 */
export interface StoreBlogsSelect<T extends boolean = true> {
  title?: T;
  handle?: T;
  commentPolicy?: T;
  templateSuffix?: T;
  shopify?:
    | T
    | {
        syncStatus?: T;
        syncMessage?: T;
        resolve?: T;
        gid?: T;
        updatedAt?: T;
        lastSyncedAt?: T;
        fingerprint?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storeMenus_select".
 */
export interface StoreMenusSelect<T extends boolean = true> {
  title?: T;
  handle?: T;
  isDefault?: T;
  items?:
    | T
    | {
        title?: T;
        type?: T;
        resource?: T;
        url?: T;
        tags?: T;
        resourceId?: T;
        itemId?: T;
        subItems?:
          | T
          | {
              title?: T;
              type?: T;
              resource?: T;
              url?: T;
              tags?: T;
              resourceId?: T;
              itemId?: T;
              subSubItems?:
                | T
                | {
                    title?: T;
                    type?: T;
                    resource?: T;
                    url?: T;
                    tags?: T;
                    resourceId?: T;
                    itemId?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  shopify?:
    | T
    | {
        syncStatus?: T;
        syncMessage?: T;
        resolve?: T;
        gid?: T;
        updatedAt?: T;
        lastSyncedAt?: T;
        fingerprint?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  eyecatch?: T;
  description?: T;
  excerpt?: T;
  slug?: T;
  publishedAt?: T;
  categories?: T;
  tags?: T;
  featured?: T;
  author?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  _order?: T;
  image?: T;
  title?: T;
  subtitle?: T;
  detailButtonUrl?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sourceUrl?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        avif480?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        avif800?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        avif1200?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        avif1600?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        webp480?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        webp800?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        webp1200?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        webp1600?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncProduct".
 */
export interface TaskSyncProduct {
  input: {
    id: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRefreshProducts".
 */
export interface TaskRefreshProducts {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncStoreResource".
 */
export interface TaskSyncStoreResource {
  input: {
    collection: string;
    id: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDeleteStoreResource".
 */
export interface TaskDeleteStoreResource {
  input: {
    collection: string;
    shopifyId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRefreshStore".
 */
export interface TaskRefreshStore {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}